spring:
  datasource:
    username: sa
    generate-unique-name: false
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
            
#  jpa:
#    hibernate:
#      ddl-auto: update
